name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - "infra/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{secrets.DIGITLOCEAN_ACCESS_TOKEN}}
      - run: doctl kubernetes cluster kubeconfig save 679ae372-8c91-495f-9935-32d57241a169
      - run: kubectl apply -f infra/k8
